Feature/#49
Komando4ediae/komando4Project pull request #50
Opened 2024-03-04 16:34 UTC by CarlosBoulder

closes #49 
Update climbing-crag-location

2024-03-04 16:34 UTC, CarlosBoulder commented
revisar @JJ

2024-03-04 16:47 UTC, JJ requested changes
Creo que ya lo hemos hablado otras veces, pero deberíais considerar convertir esto en una clase que tenga instancias y listas de todas las demás, e integrarlas aquí. Uno de los métodos podría ser lo que ahora estáis definiendo como clase.
También deberíais llamarlo con un sustantivo como *Forecaster* y no un verbo como *forecast*

2024-03-04 16:47 UTC, JJ commented on climbing-crag-forecast.js
> +    console.log(
Esto no lo había visto antes. Primero, en general una función no debe escribir en la salida si no lo indica explícitamente en el nombre. Segundo, una vez más, estáis convirtiendo en una clase lo que posiblemente deberíais considerar que es simplemente una función que tiene uno de los parámetros como entrada y otro una salida.

2024-03-05 16:38 UTC, JJ commented
This PR is not assigned to any milestone.

2024-03-05 19:40 UTC, closed without merging